name: Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: "8"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Debug dist folder
        run: ls -la dist/

      # dist成果物を "github-pages" という名前でアップロード
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist/
          if-no-files-found: error

      - name: Convert kyopro-note.md to HTML
        run: |
          pnpm add markdown-it markdown-it-katex prismjs markdown-it-prism prism-themes
          node scripts/md2html.cjs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: dist/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist